/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {Route as rootRouteImport} from "./routes/__root";
import {Route as StateRouteImport} from "./routes/state";
import {Route as PerformanceRouteImport} from "./routes/performance";
import {Route as MasterRouteImport} from "./routes/master";
import {Route as InteractivityRouteImport} from "./routes/interactivity";
import {Route as IndexRouteImport} from "./routes/index";

const StateRoute = StateRouteImport.update({
  id: "/state",
  path: "/state",
  getParentRoute: () => rootRouteImport,
} as any);
const PerformanceRoute = PerformanceRouteImport.update({
  id: "/performance",
  path: "/performance",
  getParentRoute: () => rootRouteImport,
} as any);
const MasterRoute = MasterRouteImport.update({
  id: "/master",
  path: "/master",
  getParentRoute: () => rootRouteImport,
} as any);
const InteractivityRoute = InteractivityRouteImport.update({
  id: "/interactivity",
  path: "/interactivity",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/interactivity": typeof InteractivityRoute;
  "/master": typeof MasterRoute;
  "/performance": typeof PerformanceRoute;
  "/state": typeof StateRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/interactivity": typeof InteractivityRoute;
  "/master": typeof MasterRoute;
  "/performance": typeof PerformanceRoute;
  "/state": typeof StateRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/interactivity": typeof InteractivityRoute;
  "/master": typeof MasterRoute;
  "/performance": typeof PerformanceRoute;
  "/state": typeof StateRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/interactivity" | "/master" | "/performance" | "/state";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/interactivity" | "/master" | "/performance" | "/state";
  id:
    | "__root__"
    | "/"
    | "/interactivity"
    | "/master"
    | "/performance"
    | "/state";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  InteractivityRoute: typeof InteractivityRoute;
  MasterRoute: typeof MasterRoute;
  PerformanceRoute: typeof PerformanceRoute;
  StateRoute: typeof StateRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/state": {
      id: "/state";
      path: "/state";
      fullPath: "/state";
      preLoaderRoute: typeof StateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/performance": {
      id: "/performance";
      path: "/performance";
      fullPath: "/performance";
      preLoaderRoute: typeof PerformanceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/master": {
      id: "/master";
      path: "/master";
      fullPath: "/master";
      preLoaderRoute: typeof MasterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/interactivity": {
      id: "/interactivity";
      path: "/interactivity";
      fullPath: "/interactivity";
      preLoaderRoute: typeof InteractivityRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InteractivityRoute: InteractivityRoute,
  MasterRoute: MasterRoute,
  PerformanceRoute: PerformanceRoute,
  StateRoute: StateRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type {getRouter} from "./router.tsx";
import type {createStart} from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
